"""empty message

Revision ID: 12e1632c4deb
Revises: 
Create Date: 2020-03-31 23:13:04.486325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e1632c4deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('ccxt_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'exchange', ['ccxt_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exchange', type_='unique')
    op.drop_column('exchange', 'ccxt_name')
    # ### end Alembic commands ###
