"""empty message

Revision ID: 3b864fae924d
Revises: 12e1632c4deb
Create Date: 2020-04-02 14:59:46.115307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b864fae924d'
down_revision = '12e1632c4deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('data', sa.UnicodeText(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('data_type_is_open', sa.Boolean(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchange.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_data')
    # ### end Alembic commands ###
